In [11]:
import boto3
import numpy as np
from io import BytesIO

In [14]:
s3_client = boto3.client('s3', aws_access_key_id='AKIAQTJEEW4MD27IS54B', aws_secret_access_key='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')
obj = s3_client.get_object(Bucket='script.chargepoint.data', Key='clean/Reduced/Processed_Zips/Processed_Counties/'+'San Mateo'+'_uncontrolled_load'+'.npy')
# uncontrolled_load = np.load(BytesIO(obj['Body'].read()), allow_pickle=True)

In [3]:
import time
import requests
import json
import numpy as np

In [33]:
a = np.array([1e-2,2e-2,3e-1,4e-1,5e-2,6e-2])
b = np.array([[1,2,3,4,5,6]])

In [34]:
b[:, 0:2]

array([[1, 2]])

In [21]:
c = np.array([a])
d = np.array([np.zeros(c.size)])

In [35]:
e = a.reshape((1, a.size))
e

array([[0.01, 0.02, 0.3 , 0.4 , 0.05, 0.06]])

In [36]:
e[0][0] = 2
e

array([[2.  , 0.02, 0.3 , 0.4 , 0.05, 0.06]])

In [46]:
l = e*1000
l = l.astype(int)
l

array([[2000,   20,  300,  400,   50,   60]])

In [47]:
t = 60
if t:
    print('Not zero')
else:
    print('Zero')

Not zero


In [60]:
np.clip(5,0,None)

5

In [64]:
9*10./100


0.9

In [57]:
f = 1.66666667e+04
str(f)

'16666.6667'

In [54]:
f=[1,2,3,4]
np.asarray(f)/10
# f=f/10
# f

array([0.1, 0.2, 0.3, 0.4])

In [80]:
date_ini = datetime.datetime(2019,5,22)
date_end = datetime.datetime(2019,5,26)
date_ini_request = date_ini.timestamp()*1000
date_end_request = date_end.timestamp()*1000

In [81]:
headers = {"x-api-key" : "e132e14a-0104-4e29-ad16-00c69de3e0ef"}
params = {'label': 'energy_consumed', 'start': date_ini_request, 'end': date_end_request, 'step': 3600000, 'format': 'json', 'vids': ['sf_022']}
r = requests.get('https://sdk.viriciti.com/api/v1/time/', params=params, headers=headers)
print(r.status_code)
print(r.json())

